### ISSUE TITLE
Fixing AWCC

### ISSUE THREAD

**Issue by Thiago4532** [cemkaya-mpi/Dell-G15-Controller#1]
After trying many things, I wasn't able to fix my Windows AWCC after using this script. So, I decided to read the code and try to modify some things. After making those modifications, I successfully reset the keyboard light. The solution involved removing all animations from the keyboard using elc.remove_animation. However, there was an animation that was not listed for some reason. But in the end I managed to obtain the animation ID using the `get_animation_count` command.

Later I can create a Pull Request to create a script that resets all the animations. This could help people who encounter similar problems like mine.

**Comment by cemkaya-mpi** [comment]
Hi, I thought this app might break AWCC, but I could not test it since I do not have a Windows installation. Maybe we can add a button to reset animations, so that one can do that before booting to windows?

**Comment by theRealCarneiro** [comment]
Also having this issue, good to know it's reversable then

**Comment by cemkaya-mpi** [comment]
Hi, I would like to fix this, but I do not have AWCC or Windows. I assume the problem occurs because I never remove all the animations. There used to be some flickering issues on boot, but I believe they are already fixed. If someone shares how they fixed the issue, I'd be more than happy to fix it. A pull request is also welcome. You can include elc.py and try some commands from a terminal to see if it fixes the issue.

**Comment by Thiago4532** [comment]
Oh, I forgot completely about this! I can try to make a Pull Request today.

**Comment by cemkaya-mpi** [comment]
Please let me know if the new version fixes the issue.

**Comment by cemkaya-mpi** [comment]
Feel free to reopen the issue if the new version does not work.
