### ISSUE TITLE
Program shell commands keep spilling into .bash_history

### ISSUE THREAD

**Issue by walter-gabriel** [cemkaya-mpi/Dell-G15-Controller#5]
Self explanatory. Root user bash_history gets flushed with ACPI commands.

**Comment by cemkaya-mpi** [comment]
Yes, this is due to the elevated bash shell running in the background. It is used to call ACPI methods. It would be best to design a kernel module that implements standard linux interfaces such as sysfs, debugfs, hwmon etc. and use it instead of the background shell.

However, I do not have enough time to spend on this project. Anyone is welcome to contribute.
